### ISSUE TITLE
personal notifications 

### ISSUE THREAD

**Issue by Valentyn-Kubrak** [malavsky/jira-slack#14]
Hello, very nice integration. Thank you very much. Just question: How to send notification  in Slack directly to  user private messages when ticket assgined to some user in JIRA?

**Comment by aivus** [comment]
The simple way to create list of existence users (registered in slack) and check if user from jira hook exists in you list - send direct message, otherwise - channel.

Or you can use mention to notify affected users.

**Comment by Valentyn-Kubrak** [comment]
@aivus ,
Sorry that I am taking your time, can you please just send some link where I can setup users in " jira hook "
My users in JIRA have not the same names like in Slack.

I used manual from this repo, and just used "Incoming WebHooks", where I can make this:
"check if user from jira hook exists in you list - send direct message, otherwise - channel."

Or I need to modify source code in some class?

(Thank you for quick response)

**Comment by aivus** [comment]
This feature not implemented.

You should implement it by yourself.

**Comment by Valentyn-Kubrak** [comment]
cool, thanks!
